name: Verificação de Qualidade e Lint

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  # Renomeia o job
  code-quality-check:
    runs-on: ubuntu-latest

    steps:
      # 1. Baixa o seu código do repositório
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Configura o Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Use sua versão

      # 3. Instala as dependências (agora incluindo robocop e flake8)
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # 4. Roda os Linters! (O Novo "Teste")
      - name: Rodar Robocop (Linter do Robot)
        run: robocop tests/ resources/

      - name: Rodar Flake8 (Linter do Python)
        run: flake8 lib/
